# Generated by Django 4.0.2 on 2022-02-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Name of place')),
                ('city', models.CharField(max_length=80, verbose_name='City name')),
                ('reason', models.TextField(verbose_name='Why this place')),
            ],
        ),
    ]
