# Generated by Django 4.0.2 on 2022-03-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
        migrations.AlterField(
            model_name='list',
            name='reason',
            field=models.TextField(verbose_name='Why this place?'),
        ),
    ]
