# Generated by Django 4.0.2 on 2022-03-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_list_options_alter_list_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListForAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeName', models.CharField(max_length=100, verbose_name='Name of place')),
                ('cityName', models.CharField(max_length=80, verbose_name='City name')),
            ],
            options={
                'verbose_name': 'PlaceForAdmin',
                'verbose_name_plural': 'PlacesForAdmin',
            },
        ),
    ]
