# Generated by Django 4.0.2 on 2022-03-16 19:38

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_listforadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=191)),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.filepath)),
            ],
        ),
    ]
